#!/usr/bin/env node
// Regenerate test-index.json from RAW mabl data (the live-refresh half of area-coverage-audit).
// Codifies the testid/route extraction the bootstrap did by hand.
//
// Inputs (written by the agent/CLI from mabl before running this):
//   scripts/shift-left/.raw/tests.json        <- get_mabl_tests output ({tests:[{id,name,labels,type,enabled}]})
//   scripts/shift-left/.raw/steps/<id>.json   <- mabl_get_test_steps output for each browser test
// Output:
//   scripts/shift-left/test-index.json
//
// Run: node scripts/shift-left/refresh-index.mjs    (or with a different raw dir as argv[1])

import fs from "node:fs";
import path from "node:path";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const RAW = path.resolve(argvDir() || path.join(HERE, ".raw"));
function argvDir() { const a = process.argv[2]; return a && !a.startsWith("--") ? a : null; }

// recursive walk: collect every data_testid, every [data-testid=…] in css_query, and every url
export function extract(node, tids = new Set(), urls = new Set()) {
  if (Array.isArray(node)) { for (const x of node) extract(x, tids, urls); return { tids, urls }; }
  if (node && typeof node === "object") {
    for (const [k, v] of Object.entries(node)) {
      if (k === "data_testid" && typeof v === "string") tids.add(v);
      else if (k === "css_query" && typeof v === "string") { const m = v.match(/\[data-testid="([^"]+)"\]/); if (m) tids.add(m[1]); }
      else if (k === "url" && typeof v === "string") urls.add(v);
      else extract(v, tids, urls);
    }
  }
  return { tids, urls };
}

export function normUrl(u) {
  if (/\{\{.*url.*\}\}/i.test(u)) return "/";          // {{@web.defaults.url}} etc -> base
  try { const p = new URL(u); return (p.pathname || "/") + (p.search || ""); } // strip host
  catch { return u.startsWith("/") ? u : "/" + u; }
}

export function areaLabels(labels = []) {
  return labels.filter((l) => l.startsWith("area-")).map((l) => l.slice("area-".length)).sort();
}

export function buildEntry(meta, stepsJson) {
  const { tids, urls } = extract(stepsJson);
  // keep app routes only (drop the mabl-viewer / external hosts that slipped into selector urls)
  const routes = [...new Set([...urls].map(normUrl))].filter((r) => r.startsWith("/") && !/^\/(workspaces|hc)\b/.test(r)).sort();
  return { id: meta.id, name: meta.name, testids: [...tids].sort(), routes, area: areaLabels(meta.labels) };
}

// ---- main (skipped when imported for tests) ----
if (import.meta.url === `file://${process.argv[1]}`) {
  const tests = JSON.parse(fs.readFileSync(path.join(RAW, "tests.json"), "utf8")).tests || [];
  const browser = tests.filter((t) => t.type === "browser" && t.enabled);
  const out = [];
  for (const t of browser) {
    const sp = path.join(RAW, "steps", t.id + ".json");
    if (!fs.existsSync(sp)) { console.warn(`! no steps for ${t.id} (${t.name}) — skipped`); continue; }
    out.push(buildEntry(t, JSON.parse(fs.readFileSync(sp, "utf8"))));
  }
  const dest = path.join(HERE, "test-index.json");
  fs.writeFileSync(dest, JSON.stringify({ _comment: "Auto-generated by refresh-index.mjs from live mabl data.", tests: out }, null, 2) + "\n");
  console.log(`wrote ${out.length} tests -> ${path.relative(process.cwd(), dest)}`);
}
