import type { Product, User, Order } from "./types";
import { hashPassword } from "./auth-crypto";

const ISO_EPOCH = "2026-01-15T12:00:00.000Z";

export const SEED_PRODUCTS: Product[] = [
  // Sticks
  {
    id: "p-stk-001",
    slug: "apex-velocity-pro-stick",
    name: "Apex Velocity Pro Stick",
    description:
      "Pro-level composite stick with a low kick point and a textured grip. Snaps shots off like a slap bet.",
    category: "sticks",
    brand: "Apex",
    priceCents: 28999,
    salePriceCents: 19999,
    position: "player",
    hand: "right",
    size: "Senior",
    flex: 85,
    stock: 18,
    rating: 4.7,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-stk-002",
    slug: "ironline-blizzard-jr-stick",
    name: "Ironline Blizzard Jr Stick",
    description:
      "Lightweight junior stick tuned for quick release. Our bestselling pick for U14s.",
    category: "sticks",
    brand: "Ironline",
    priceCents: 14999,
    salePriceCents: 8999,
    position: "player",
    hand: "left",
    size: "Junior",
    flex: 50,
    stock: 32,
    rating: 4.5,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-stk-003",
    slug: "glacier-edge-intermediate-stick",
    name: "Glacier Edge Intermediate Stick",
    description:
      "Balanced composite shaft with a mid kick point. Built for intermediate players stepping up their game.",
    category: "sticks",
    brand: "Glacier",
    priceCents: 19999,
    salePriceCents: null,
    position: "player",
    hand: "right",
    size: "Intermediate",
    flex: 65,
    stock: 14,
    rating: 4.4,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-stk-004",
    slug: "coldfire-rookie-wood-stick",
    name: "Coldfire Rookie Wood Stick",
    description:
      "Classic laminated wood stick for youth players. Durable, honest, and easy on the wallet.",
    category: "sticks",
    brand: "Coldfire",
    priceCents: 3499,
    salePriceCents: 1999,
    position: "player",
    hand: "left",
    size: "Youth",
    flex: 40,
    stock: 60,
    rating: 4.1,
    createdAt: ISO_EPOCH,
  },

  // Skates
  {
    id: "p-skt-001",
    slug: "apex-supreme-player-skates",
    name: "Apex Supreme Player Skates",
    description:
      "Heat-moldable boot with a stiff carbon quarter package. Built for speed and support through three periods.",
    category: "skates",
    brand: "Apex",
    priceCents: 54999,
    salePriceCents: 39999,
    position: "player",
    hand: "n/a",
    size: "10 US",
    flex: null,
    stock: 9,
    rating: 4.8,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-skt-002",
    slug: "northbound-tour-intermediate-skates",
    name: "Northbound Tour Intermediate Skates",
    description:
      "Mid-tier skate designed for the weekend beer-league warrior. All-day comfort, reinforced tendon guard.",
    category: "skates",
    brand: "Northbound",
    priceCents: 24999,
    salePriceCents: 17999,
    position: "player",
    hand: "n/a",
    size: "9 US",
    flex: null,
    stock: 22,
    rating: 4.3,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-skt-003",
    slug: "glacier-lightweight-jr-skates",
    name: "Glacier Lightweight Jr Skates",
    description:
      "Lightweight junior skates with an easy lacing system. Perfect for growing skaters.",
    category: "skates",
    brand: "Glacier",
    priceCents: 12999,
    salePriceCents: null,
    position: "player",
    hand: "n/a",
    size: "5 US",
    flex: null,
    stock: 28,
    rating: 4.2,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-skt-004",
    slug: "ironline-goalie-skates",
    name: "Ironline Goalie Skates",
    description:
      "Low-profile goalie skates with reinforced side protection and a deeper hollow for crease mobility.",
    category: "skates",
    brand: "Ironline",
    priceCents: 44999,
    salePriceCents: 29999,
    position: "goalie",
    hand: "n/a",
    size: "10 US",
    flex: null,
    stock: 6,
    rating: 4.6,
    createdAt: ISO_EPOCH,
  },

  // Helmets
  {
    id: "p-hlm-001",
    slug: "apex-fortress-helmet",
    name: "Apex Fortress Helmet",
    description:
      "Dual-density foam and a tool-free fit system. HECC certified. Pairs with combo cage or visor.",
    category: "helmets",
    brand: "Apex",
    priceCents: 15999,
    salePriceCents: 11999,
    position: "any",
    hand: "n/a",
    size: "M",
    flex: null,
    stock: 24,
    rating: 4.5,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-hlm-002",
    slug: "ironline-guardpro-helmet",
    name: "Ironline GuardPro Helmet",
    description:
      "Budget-friendly helmet with integrated chin cup. Great starter helmet for new players.",
    category: "helmets",
    brand: "Ironline",
    priceCents: 7999,
    salePriceCents: 4999,
    position: "any",
    hand: "n/a",
    size: "L",
    flex: null,
    stock: 30,
    rating: 4.0,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-hlm-003",
    slug: "glacier-rinkshell-helmet",
    name: "Glacier RinkShell Helmet",
    description:
      "Lightweight shell with airflow channels. Comfortable for long practices and back-to-back tournaments.",
    category: "helmets",
    brand: "Glacier",
    priceCents: 10999,
    salePriceCents: null,
    position: "any",
    hand: "n/a",
    size: "S",
    flex: null,
    stock: 18,
    rating: 4.3,
    createdAt: ISO_EPOCH,
  },

  // Gloves
  {
    id: "p-glv-001",
    slug: "apex-gripforce-gloves",
    name: "Apex GripForce Gloves",
    description:
      "4-roll traditional cut with a synthetic Nash palm. Drops the gloves is optional; wearing them is required.",
    category: "gloves",
    brand: "Apex",
    priceCents: 13999,
    salePriceCents: 9999,
    position: "player",
    hand: "n/a",
    size: "14 in",
    flex: null,
    stock: 15,
    rating: 4.6,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-glv-002",
    slug: "coldfire-vintage-gloves",
    name: "Coldfire Vintage Gloves",
    description:
      "Old-school tapered fit with modern foam inserts. Looks like 1994, protects like 2026.",
    category: "gloves",
    brand: "Coldfire",
    priceCents: 8999,
    salePriceCents: 5999,
    position: "player",
    hand: "n/a",
    size: "13 in",
    flex: null,
    stock: 20,
    rating: 4.4,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-glv-003",
    slug: "glacier-agility-gloves",
    name: "Glacier Agility Gloves",
    description:
      "Anatomical fit with a flexible cuff. Built for defensemen who live along the boards.",
    category: "gloves",
    brand: "Glacier",
    priceCents: 11999,
    salePriceCents: null,
    position: "player",
    hand: "n/a",
    size: "14 in",
    flex: null,
    stock: 12,
    rating: 4.5,
    createdAt: ISO_EPOCH,
  },

  // Pads
  {
    id: "p-pad-001",
    slug: "saberline-elite-shin-pads",
    name: "Saberline Elite Shin Pads",
    description:
      "Molded knee cradle with reinforced shin shield. Adjustable strap system fits any calf size.",
    category: "pads",
    brand: "Saberline",
    priceCents: 9999,
    salePriceCents: 6999,
    position: "player",
    hand: "n/a",
    size: "15 in",
    flex: null,
    stock: 18,
    rating: 4.4,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-pad-002",
    slug: "strongside-shoulder-pads",
    name: "Strongside Shoulder Pads",
    description:
      "Low-profile shoulder caps with floating bicep guards. For forwards who hate bulk.",
    category: "pads",
    brand: "Strongside",
    priceCents: 13999,
    salePriceCents: 9499,
    position: "player",
    hand: "n/a",
    size: "L",
    flex: null,
    stock: 10,
    rating: 4.2,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-pad-003",
    slug: "apex-flex-elbow-pads",
    name: "Apex Flex Elbow Pads",
    description:
      "Three-piece wraparound cap with a lock-strap. Comfortable enough to forget you're wearing them.",
    category: "pads",
    brand: "Apex",
    priceCents: 7499,
    salePriceCents: null,
    position: "player",
    hand: "n/a",
    size: "M",
    flex: null,
    stock: 25,
    rating: 4.3,
    createdAt: ISO_EPOCH,
  },

  // Jerseys
  {
    id: "p-jsy-001",
    slug: "blank-home-jersey-white",
    name: "Blank Home Jersey (White)",
    description:
      "Team-ready blank jersey in tournament white. Add your crest and sweater number at checkout.",
    category: "jerseys",
    brand: "Cheap Shot",
    priceCents: 6999,
    salePriceCents: 4999,
    position: "any",
    hand: "n/a",
    size: "L",
    flex: null,
    stock: 40,
    rating: 4.6,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-jsy-002",
    slug: "blank-away-jersey-black",
    name: "Blank Away Jersey (Black)",
    description: "Matte black away jersey. Intimidating even before warm-ups.",
    category: "jerseys",
    brand: "Cheap Shot",
    priceCents: 6999,
    salePriceCents: 4999,
    position: "any",
    hand: "n/a",
    size: "L",
    flex: null,
    stock: 40,
    rating: 4.7,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-jsy-003",
    slug: "practice-jersey-reversible",
    name: "Practice Jersey (Reversible)",
    description:
      "Reversible navy/white practice jersey. Change lines without a wardrobe change.",
    category: "jerseys",
    brand: "Cheap Shot",
    priceCents: 3999,
    salePriceCents: 2499,
    position: "any",
    hand: "n/a",
    size: "M",
    flex: null,
    stock: 55,
    rating: 4.4,
    createdAt: ISO_EPOCH,
  },

  // Pucks
  {
    id: "p-pck-001",
    slug: "official-game-pucks-6-pack",
    name: "Official Game Pucks (6-pack)",
    description: "Regulation weight and diameter. Vulcanized rubber. For league play.",
    category: "pucks",
    brand: "Cheap Shot",
    priceCents: 1999,
    salePriceCents: 1299,
    position: "any",
    hand: "n/a",
    size: "6-pack",
    flex: null,
    stock: 100,
    rating: 4.8,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-pck-002",
    slug: "practice-pucks-12-pack",
    name: "Practice Pucks (12-pack)",
    description: "Bulk practice pucks. Slightly heavier weight for stickhandling drills.",
    category: "pucks",
    brand: "Cheap Shot",
    priceCents: 2999,
    salePriceCents: null,
    position: "any",
    hand: "n/a",
    size: "12-pack",
    flex: null,
    stock: 75,
    rating: 4.5,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-pck-003",
    slug: "glow-in-the-dark-puck",
    name: "Glow-in-the-Dark Puck",
    description: "Novelty glow puck. Great for pond hockey after sunset.",
    category: "pucks",
    brand: "Cheap Shot",
    priceCents: 999,
    salePriceCents: 599,
    position: "any",
    hand: "n/a",
    size: "Single",
    flex: null,
    stock: 200,
    rating: 4.2,
    createdAt: ISO_EPOCH,
  },

  // Goalie gear
  {
    id: "p-gol-001",
    slug: "crease-guardian-leg-pads",
    name: "Crease Guardian Leg Pads",
    description:
      "35+1 butterfly leg pads with reinforced inner rolls. Quick flex profile for aggressive netminders.",
    category: "goalie-gear",
    brand: "Crease Guardian",
    priceCents: 89999,
    salePriceCents: 64999,
    position: "goalie",
    hand: "n/a",
    size: "35+1",
    flex: null,
    stock: 4,
    rating: 4.8,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-gol-002",
    slug: "crease-guardian-chest-protector",
    name: "Crease Guardian Chest Protector",
    description:
      "Modular chest protector with removable sternum plate. Built to shrug off slappers from the blue line.",
    category: "goalie-gear",
    brand: "Crease Guardian",
    priceCents: 49999,
    salePriceCents: 34999,
    position: "goalie",
    hand: "n/a",
    size: "L",
    flex: null,
    stock: 5,
    rating: 4.7,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-gol-003",
    slug: "crease-guardian-blocker",
    name: "Crease Guardian Blocker",
    description: "Square blocker face with curved sidewall. Ideal rebound control for butterfly goalies.",
    category: "goalie-gear",
    brand: "Crease Guardian",
    priceCents: 24999,
    salePriceCents: 18999,
    position: "goalie",
    hand: "right",
    size: "Senior",
    flex: null,
    stock: 7,
    rating: 4.6,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-gol-004",
    slug: "crease-guardian-catcher",
    name: "Crease Guardian Catcher",
    description: "Single-T web catcher with a 590 break angle. Snatches pucks like a beer-league hero.",
    category: "goalie-gear",
    brand: "Crease Guardian",
    priceCents: 24999,
    salePriceCents: 18999,
    position: "goalie",
    hand: "left",
    size: "Senior",
    flex: null,
    stock: 6,
    rating: 4.6,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-gol-005",
    slug: "crease-guardian-mask",
    name: "Crease Guardian Mask",
    description:
      "Certified fiberglass composite shell. Paint-ready for custom designs. Because the mask is the canvas.",
    category: "goalie-gear",
    brand: "Crease Guardian",
    priceCents: 39999,
    salePriceCents: 27999,
    position: "goalie",
    hand: "n/a",
    size: "M",
    flex: null,
    stock: 8,
    rating: 4.7,
    createdAt: ISO_EPOCH,
  },

  // Accessories
  {
    id: "p-acc-001",
    slug: "skate-laces-96-inch-black",
    name: "Skate Laces (96 in, Black)",
    description: "Waxed skate laces. Pack of 2. Because loose laces = bench splinters.",
    category: "accessories",
    brand: "Cheap Shot",
    priceCents: 699,
    salePriceCents: 399,
    position: "any",
    hand: "n/a",
    size: "96 in",
    flex: null,
    stock: 150,
    rating: 4.5,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-acc-002",
    slug: "stick-tape-black-3-pack",
    name: "Stick Tape (Black, 3-pack)",
    description: "Cloth hockey tape. Three rolls. Guaranteed to come off your stick exactly when you don't want it to.",
    category: "accessories",
    brand: "Cheap Shot",
    priceCents: 899,
    salePriceCents: 599,
    position: "any",
    hand: "n/a",
    size: "3-pack",
    flex: null,
    stock: 120,
    rating: 4.6,
    createdAt: ISO_EPOCH,
  },
  {
    id: "p-acc-003",
    slug: "skate-guards-soakers",
    name: "Skate Guards (Soakers)",
    description: "Terrycloth blade soakers. Absorbent. Protects blades in the bag between games.",
    category: "accessories",
    brand: "Cheap Shot",
    priceCents: 1299,
    salePriceCents: null,
    position: "any",
    hand: "n/a",
    size: "One size",
    flex: null,
    stock: 80,
    rating: 4.3,
    createdAt: ISO_EPOCH,
  },
];

export const SEED_USERS: User[] = [
  {
    id: "u-001",
    email: "demo@cheapshot.test",
    passwordHash: hashPassword("demo1234"),
    name: "Demo Customer",
    role: "customer",
    createdAt: ISO_EPOCH,
  },
  {
    id: "u-002",
    email: "admin@cheapshot.test",
    passwordHash: hashPassword("admin1234"),
    name: "Admin User",
    role: "admin",
    createdAt: ISO_EPOCH,
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: "o-1001",
    userId: "u-001",
    guestEmail: null,
    lines: [
      {
        productId: "p-stk-001",
        name: "Apex Velocity Pro Stick",
        unitPriceCents: 19999,
        quantity: 1,
      },
      {
        productId: "p-acc-002",
        name: "Stick Tape (Black, 3-pack)",
        unitPriceCents: 599,
        quantity: 2,
      },
    ],
    subtotalCents: 21197,
    taxCents: 1696,
    shippingCents: 999,
    totalCents: 23892,
    status: "delivered",
    shippingAddress: {
      name: "Demo Customer",
      street: "12 Rink Road",
      city: "Minneapolis",
      state: "MN",
      postalCode: "55401",
      country: "US",
    },
    createdAt: "2026-03-12T09:12:00.000Z",
  },
];
